{
  "name": "{{.ProjectName}}",
  "version": "1.0.0",
  "description": "{{.Description}}",
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "test:unit": "jest --testPathPattern=unit",
    "test:integration": "jest --testPathPattern=integration",
    "test:system": "jest --testPathPattern=system",
    "test:e2e": "detox test",
    "test:e2e:ios": "detox test --configuration ios.sim.release",
    "test:e2e:android": "detox test --configuration android.emu.release",
    "test:coverage": "jest --coverage --watchAll=false",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "lint:fix": "eslint . --ext .js,.jsx,.ts,.tsx --fix",
    "build:ios": "cd ios && xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphoneos -derivedDataPath build",
    "build:android": "cd android && ./gradlew assembleRelease",
    "build:android:bundle": "cd android && ./gradlew bundleRelease",
    "deploy:ios": "fastlane ios release",
    "deploy:android": "fastlane android release",
    "screenshots": "fastlane screenshots",
    "bump-version": "fastlane bump_version"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-native": "^0.72.6",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-native-community/geolocation": "^3.1.0",
    "@react-native-community/cameraroll": "^4.1.2",
    "@react-native-firebase/app": "^18.7.3",
    "@react-native-firebase/auth": "^18.7.3",
    "@react-native-firebase/firestore": "^18.7.3",
    "@react-native-firebase/messaging": "^18.7.3",
    "@react-native-firebase/analytics": "^18.7.3",
    "@react-native-firebase/perf": "^18.7.3",
    "react-native-permissions": "^4.1.0",
    "react-native-image-picker": "^7.1.0",
    "react-native-contacts": "^7.0.5",
    "react-native-sensors": "^7.3.6",
    "@react-native-community/netinfo": "^11.2.1",
    "react-native-share": "^10.0.2",
    "@stripe/stripe-react-native": "^0.35.1",
    "@sentry/react-native": "^5.16.0",
    "redux": "^4.2.1",
    "react-redux": "^8.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "@testing-library/react-native": "^12.4.3",
    "@testing-library/jest-native": "^5.4.3",
    "@testing-library/react-hooks": "^8.0.1",
    "babel-jest": "^29.2.1",
    "detox": "^20.13.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "fastlane": "^2.217.0",
    "@types/jest": "^29.5.11",
    "@types/node": "^20.10.6",
    "husky": "^8.0.3",
    "lint-staged": "^15.2.0",
    "js-yaml": "^4.1.0"
  }
}